use elidek;
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Tyler Perry''s A Madea Christmas', 'Quality-focused actuating website', 1, '2022-06-09');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Variety (Varieté)', 'Multi-tiered eco-centric customer loyalty', 1, '2022-07-25');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Mrs. Winterbourne', 'Organic 24/7 open architecture', 1, '2023-03-07');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Muriel, or The Time of Return (Muriel ou Le temps d''un retour)', 'Reactive human-resource projection', 1, '2022-11-11');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Maximum Risk', 'Secured full-range success', 1, '2022-07-18');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Hitman''s Run', 'Ergonomic 24 hour encoding', 1, '2023-03-31');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Into Great Silence (Die große Stille)', 'Public-key mobile data-warehouse', 2, '2022-11-14');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Spider''s Stratagem, The (Strategia del ragno)', 'Down-sized 5th generation capability', 2, '2022-06-23');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('North Star, The', 'Exclusive upward-trending throughput', 2, '2023-03-17');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Dark City', 'Up-sized leading edge core', 2, '2022-09-21');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('That Hamilton Woman', 'Cross-platform modular artificial intelligence', 2, '2023-04-25');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Running On Karma (Daai Zek Lou)', 'Multi-tiered impactful array', 2, '2022-06-10');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Jesse Stone: Stone Cold', 'Face to face composite flexibility', 2, '2023-01-16');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('The Fox and the Hound 2', 'Multi-tiered explicit focus group', 3, '2023-05-16');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Dracula Has Risen from the Grave', 'Front-line eco-centric product', 3, '2022-09-29');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Crazy Beautiful You', 'Public-key 24/7 protocol', 3, '2023-05-20');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Je préfère qu''on reste amis', 'Profound attitude-oriented installation', 3, '2023-04-01');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Asier ETA biok', 'Robust bi-directional parallelism', 3, '2023-03-10');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Signs of Life (Lebenszeichen)', 'Organized composite system engine', 3, '2022-07-27');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Square, The (Al Midan)', 'Implemented fresh-thinking extranet', 3, '2023-03-18');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Dead Man''s Shoes', 'Universal holistic policy', 3, '2022-12-12');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Mile... Mile & a Half', 'Focused impactful circuit', 4, '2023-05-01');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('DOA: Dead or Alive', 'Innovative 6th generation project', 4, '2023-02-25');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Mystery of the Third Planet, The (Tayna tretey planety)', 'Multi-tiered exuding projection', 4, '2022-09-05');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Dikkenek', 'Synergistic systematic extranet', 4, '2023-01-09');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Forks Over Knives', 'Balanced leading edge intranet', 4, '2022-08-26');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Blackbird', 'Function-based asynchronous extranet', 4, '2023-02-03');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('White Fang 2: Myth of the White Wolf', 'Face to face secondary open architecture', 4, '2022-09-18');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Hans Christian Andersen', 'Versatile incremental concept', 4, '2023-05-18');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('They Won''t Forget', 'Implemented systemic throughput', 5, '2023-02-17');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Cesar & Rosalie (César et Rosalie)', 'Distributed multi-state leverage', 5, '2022-08-01');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Age of Tomorrow', 'Progressive neutral Graphic Interface', 6, '2023-02-09');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Mr. Nobody', 'Expanded responsive encryption', 7, '2023-05-03');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Decoys 2: Alien Seduction ', 'Assimilated well-modulated capacity', 7, '2022-07-22');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Trip to Bountiful, The', 'Assimilated uniform protocol', 8, '2023-04-20');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Amanece, que no es poco', 'Expanded dedicated application', 8, '2022-09-23');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('To Faro (Mein Freund aus Faro)', 'Robust static project', 8, '2022-10-12');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Teen Wolf', 'Compatible exuding paradigm', 9, '2022-11-19');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Triad Underworld (Gong wu) (Jiang Hu)', 'Advanced solution-oriented matrices', 9, '2022-07-16');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Out Late ', 'Seamless 4th generation functionalities', 9, '2022-08-31');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Strange Circus (Kimyô na sâkasu)', 'Customizable full-range leverage', 9, '2022-10-25');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Don''t Drink the Water', 'Organic value-added moderator', 10, '2023-02-04');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Down and Out with the Dolls', 'Exclusive neutral core', 11, '2022-10-31');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Resident Evil: Degeneration (Baiohazâdo: Dijenerêshon)', 'Future-proofed exuding migration', 12, '2022-08-15');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Dr. No', 'Self-enabling 24 hour firmware', 13, '2022-07-12');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Broadway Melody of 1940', 'Upgradable methodical complexity', 14, '2022-09-19');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Central Station (Central do Brasil)', 'User-centric client-driven encoding', 15, '2022-07-31');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Black Cauldron, The', 'Self-enabling optimal concept', 16, '2022-08-02');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('Shinjuku Incident (San suk si gin)', 'Self-enabling bandwidth-monitored toolset', 17, '2023-05-07');
insert into assignments (assign_title, assign_summary, p_id, due_to) values ('White Zombie', 'Advanced mobile project', 18, '2022-10-05');
