use elidek;
insert into programs (prog_name, prog_address) values ('Cyperaceae', 'Mathematics');
insert into programs (prog_name, prog_address) values ('Peltulaceae', 'Agriculture');
insert into programs (prog_name, prog_address) values ('Betulaceae', 'Sports medicine');
insert into programs (prog_name, prog_address) values ('Asteraceae', 'Mathematics');
insert into programs (prog_name, prog_address) values ('Astereceae', 'Information Technologies');
insert into programs (prog_name, prog_address) values ('Astericeae', 'Information Technologies');
insert into programs (prog_name, prog_address) values ('Heliconiaceae', 'Agriculture');
insert into programs (prog_name, prog_address) values ('Nyctaginaceae', 'Agriculture');
insert into programs (prog_name, prog_address) values ('Rhamnaceae', 'Biology');
insert into programs (prog_name, prog_address) values ('Esteraceae', 'Biology');
insert into programs (prog_name, prog_address) values ('Dipsacaceae', 'Biology');
insert into programs (prog_name, prog_address) values ('Fabaceae', 'Information Technologies');
insert into programs (prog_name, prog_address) values ('Ranunculaceae', 'Electronics');
insert into programs (prog_name, prog_address) values ('Febiceae', 'Environmental');
insert into programs (prog_name, prog_address) values ('Astiroceae', 'Mathematics');
insert into programs (prog_name, prog_address) values ('Dryopteridaceae', 'Agriculture');
insert into programs (prog_name, prog_address) values ('Orchidaceae', 'Engineering');
insert into programs (prog_name, prog_address) values ('Rosaceae', 'Environmental');
insert into programs (prog_name, prog_address) values ('Euphorbiaceae', 'Civil engineering');
insert into programs (prog_name, prog_address) values ('Iridaceae', 'Sports medicine');
insert into programs (prog_name, prog_address) values ('Boraginaceae', 'Information Technologies');
insert into programs (prog_name, prog_address) values ('Fabiceae', 'Electronics');
insert into programs (prog_name, prog_address) values ('Dryopteridoceae', 'Agriculture');
insert into programs (prog_name, prog_address) values ('Pteridaceae', 'Sports medicine');
insert into programs (prog_name, prog_address) values ('Tamaricaceae', 'Engineering');
insert into programs (prog_name, prog_address) values ('Cladoniaceae', 'Environmental');
insert into programs (prog_name, prog_address) values ('Asteracie', 'Engineering');
insert into programs (prog_name, prog_address) values ('Melaspileaceae', 'Civil engineering');
insert into programs (prog_name, prog_address) values ('Bacidiaceae', 'Chemistry');
insert into programs (prog_name, prog_address) values ('Cyperacoe', 'Mathematics');
insert into programs (prog_name, prog_address) values ('Asteracae', 'Sports medicine');
insert into programs (prog_name, prog_address) values ('Asteracce', 'Sports medicine');
insert into programs (prog_name, prog_address) values ('Brassicaceae', 'Civil engineering');
insert into programs (prog_name, prog_address) values ('Caprifoliaceae', 'Environmental');
insert into programs (prog_name, prog_address) values ('Lecanoraceae', 'Chemistry');
insert into programs (prog_name, prog_address) values ('Liliaceae', 'Information Technologies');
insert into programs (prog_name, prog_address) values ('Apocynaceae', 'Biology');
insert into programs (prog_name, prog_address) values ('Brassicage', 'Chemistry');
insert into programs (prog_name, prog_address) values ('Juncaceae', 'Electronics');
insert into programs (prog_name, prog_address) values ('Cyperdaceae', 'Chemistry');
insert into programs (prog_name, prog_address) values ('Solanaceae', 'Biology');
insert into programs (prog_name, prog_address) values ('Asclepiadaceae', 'Biology');
insert into programs (prog_name, prog_address) values ('Acarosporaceae', 'Engineering');
insert into programs (prog_name, prog_address) values ('Caryophyllaceae', 'Engineering');
insert into programs (prog_name, prog_address) values ('Fabace', 'Chemistry');
insert into programs (prog_name, prog_address) values ('Polygonaceae', 'Environmental');
insert into programs (prog_name, prog_address) values ('Brassicocae', 'Biology');
insert into programs (prog_name, prog_address) values ('Lichinaceae', 'Civil engineering');
insert into programs (prog_name, prog_address) values ('Fagaceae', 'Engineering');
insert into programs (prog_name, prog_address) values ('Rhaceae', 'Biology');
